发生在try中的代码不会让程序死掉

try是同步的，异步的不能捕获

try具有块级作用域

return也会进入finally，在catch里throw也会进入，但是放在函数末尾的不会
